"""
True agentic orchestration.

Gemini is the brain — it decides what to search, how to reason, and what to say.
We provide it with three tools: search_showtimes, get_seat_availability, set_release_watch.
All responses (including rationale and plan summaries) are generated by the LLM.
"""

from __future__ import annotations

import json
from datetime import datetime, timedelta
from typing import Any
from uuid import uuid4

from sqlmodel import Session, select

from app.agents.llm import run_agent_loop
from app.models import Movie, Screen, Showtime, Theatre
from app.services.discovery import discover_showtimes, enrich_showtime
from app.services.planning import generate_plans
from app.services.preferences import get_or_create_memory, update_memory_from_intent
from app.services.release_monitoring import create_release_subscription
from app.services.seats import auto_select_seats, get_seat_map
from app.services.workflow import (
    create_agent_session,
    log_workflow_event,
    replace_plans,
    update_agent_session,
)

# In-memory conversation history store (keyed by session_key)
# In production, persist this in Redis with a TTL
_HISTORY_STORE: dict[str, list[dict]] = {}


def _get_history(session_key: str) -> list[dict]:
    return _HISTORY_STORE.get(session_key, [])


def _save_history(session_key: str, history: list[dict]) -> None:
    # Keep last 20 turns to stay within context limits
    _HISTORY_STORE[session_key] = history[-20:]


def _build_tool_executor(db: Session, intent_context: dict[str, Any]):
    """Returns a callable that Gemini can invoke for each tool."""

    def execute(tool_name: str, args: dict) -> dict[str, Any]:
        if tool_name == "search_showtimes":
            return _tool_search_showtimes(db, args, intent_context)
        if tool_name == "get_seat_availability":
            return _tool_get_seat_availability(db, args)
        if tool_name == "set_release_watch":
            return _tool_set_release_watch(db, args, intent_context)
        return {"error": f"Unknown tool: {tool_name}"}

    return execute


def _tool_search_showtimes(db: Session, args: dict, ctx: dict) -> dict[str, Any]:
    """Execute showtime search and return structured results for the LLM."""
    city = args.get("city") or ctx.get("city") or "Bengaluru"
    movie_title = args.get("movie_title")
    genre = args.get("genre")
    fmt = args.get("format")
    party_size = int(args.get("party_size") or ctx.get("seat_count") or 2)
    budget_max = args.get("budget_max")
    date_hint = args.get("date_hint", "")

    # Build a synthetic intent dict for the existing discovery engine
    now = datetime.utcnow()
    time_window = None
    if "tonight" in date_hint or "evening" in date_hint:
        time_window = "today_evening"
    elif "weekend" in date_hint:
        time_window = "weekend"
    elif "morning" in date_hint or "afternoon" in date_hint:
        time_window = "daytime"

    intent = {
        "movie": movie_title,
        "city": city,
        "genre": genre,
        "format": fmt,
        "party_size": party_size,
        "budget_max": budget_max,
        "time_window": time_window,
        "experience_mode": "balanced",
        "preferred_window_start": now.isoformat(),
        "preferred_window_end": (now + timedelta(days=3)).isoformat(),
    }

    candidates = discover_showtimes(db, intent, limit=20)

    if not candidates:
        return {
            "count": 0,
            "showtimes": [],
            "plans": [],
            "message": f"No showtimes found in {city} matching those criteria.",
        }

    plans = generate_plans(db, intent, candidates)

    # Format showtimes compactly for the LLM context
    showtime_summaries = [
        {
            "showtime_id": c["id"],
            "movie": c["movie_title"],
            "theatre": c["theatre_name"],
            "city": c["city"],
            "format": c["format"],
            "start_time": c["start_time"],
            "price_per_seat": c["base_price"],
            "total_for_party": round(c["base_price"] * party_size, 0),
            "rating": c.get("movie_rating"),
            "genre": c.get("movie_genre"),
        }
        for c in candidates[:8]
    ]

    return {
        "count": len(candidates),
        "showtimes": showtime_summaries,
        "plans": plans,
        "party_size": party_size,
        "city": city,
    }


def _tool_get_seat_availability(db: Session, args: dict) -> dict[str, Any]:
    showtime_id = int(args["showtime_id"])
    party_size = int(args.get("party_size") or 2)

    showtime = db.exec(select(Showtime).where(Showtime.id == showtime_id)).first()
    if not showtime:
        return {"error": "Showtime not found"}

    seat_map = get_seat_map(db, showtime_id)
    suggested = auto_select_seats(seat_map, party_size)

    available_count = sum(
        1 for row in seat_map for seat in row if seat.get("status") == "AVAILABLE"
    )

    return {
        "showtime_id": showtime_id,
        "available_count": available_count,
        "suggested_seats": suggested,
        "party_size": party_size,
        "seat_map_url": f"/seats/{showtime_id}",
        "note": f"Best {party_size} seats are {', '.join(suggested[:party_size]) if suggested else 'being calculated'}. Click Open Seat Map to select and hold them.",
    }


def _tool_set_release_watch(db: Session, args: dict, ctx: dict) -> dict[str, Any]:
    movie_title = args.get("movie_title", "")
    city = args.get("city") or ctx.get("city") or "Bengaluru"
    party_size = int(args.get("party_size") or ctx.get("seat_count") or 2)
    user_id = ctx.get("user_id")
    session_key = ctx.get("session_key") or f"guest-{uuid4().hex[:12]}"

    subscription = create_release_subscription(
        db,
        session_key=session_key,
        user_id=user_id,
        movie_title=movie_title,
        city=city,
        party_size=party_size,
    )

    return {
        "subscription_id": subscription.id,
        "movie": movie_title,
        "city": city,
        "party_size": party_size,
        "status": "ACTIVE",
        "message": f"Release watch set for {movie_title} in {city}. You'll be notified when bookings open.",
    }


def run_agentic_planning(
    session: Session,
    user_id: int | None,
    message: str,
    context: dict[str, Any] | None = None,
) -> dict[str, Any]:
    context = context or {}
    session_key = context.get("session_key") or f"guest-{uuid4().hex[:12]}"
    context["user_id"] = user_id
    context["session_key"] = session_key

    # Load conversation history for this session
    history = _get_history(session_key)

    # Build and run the agentic loop
    tool_executor = _build_tool_executor(session, context)
    result = run_agent_loop(
        message=message,
        history=history,
        tool_executor=tool_executor,
    )

    # Save updated history (user turn + model turn)
    new_history = list(history)
    new_history.append({"role": "user", "parts": [message]})
    new_history.append({"role": "model", "parts": [result["text"]]})
    _save_history(session_key, new_history)

    # Determine response type for frontend
    plans = result.get("plans", [])
    showtimes = result.get("showtimes", [])

    if plans:
        return {
            "type": "agent_plan",
            "message": result["text"],
            "data": {
                "plans": plans,
                "top_candidates": showtimes,
            },
            "context": {
                "session_key": session_key,
                "city": context.get("city"),
                "seat_count": context.get("seat_count", 2),
            },
            "trace": result["trace"],
        }
    elif showtimes:
        return {
            "type": "showtimes",
            "message": result["text"],
            "data": showtimes,
            "context": {"session_key": session_key},
            "trace": result["trace"],
        }
    else:
        return {
            "type": "message",
            "message": result["text"],
            "context": {"session_key": session_key},
            "trace": result["trace"],
        }
