apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: ticketly
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: ticketly
            - name: POSTGRES_PASSWORD
              value: ticketly
            - name: POSTGRES_DB
              value: ticketly
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: ticketly
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432

